version: "3.7" 

services:
  php:
    build:
      context: .
      args:
        ENV: development
    container_name: php
    ports:
      - "88:80"
    volumes:
      - ".:/app"
    working_dir: /app
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: "test_db"
      TZ: "America/Sao_Paulo"
      PGTZ: "America/Sao_Paulo"
    tmpfs:
      - /var/lib/postgresql/data
